export const surpriseMePrompts = [
  'A gaming chair crafted to resemble a raw lemon, upholstered in suede, ultra-meteor glow',
  'A surreal watercolor mural in the style of René Magritte: a checkerboard dog floating among umbrella clouds',
  'Stuffed rabbits exploring lantern-lit market stalls in Kyoto, nishiki-e woodblock print style',
  'An acrylic cut-out by Miro of a cyborg arm wrestling a grandmaster, bold abstract shapes',
  'A koala mad scientist pouring glowing elixirs in a neon-lit lab, vector illustration',
  'Design a giant mosaic honoring Rosa Parks, stencil-graffiti street-art style',
  "Macro 50mm shot of two hamsters in Bali, each sporting tiny goggles and carrying mini skateboards, sun-drenched digital photo",
  '3D render of a pastel koi fish weaving through a coral reef tank, gradient teal background',
  'A cosmonaut sipping cocktails in a pixel-art beach bar, synth-pop palette',
  'Oil portrait of a capybara in Ottoman royal vestments and a jeweled tiara, moody chiaroscuro',
  'A Tiffany-style stained-glass panel depicting tacos and salsa bowls in jewel hues',
  'Charcoal and gouache sketch of a neon skyline with hovering drones, soft pastel fog',
  'A moonlit atrium with twin plunge pools—one emerald, one lavender—framed by arched glass, vector art',
  'A tarot-reading corgi divining your future inside a giant donut crystal ball, neon digital painting',
  '"A Harbor Seal with a Turban" reimagined in the chiaroscuro of Caravaggio, oil on canvas',
  'Oil pastel illustration of a grumpy raccoon piloting a starliner through electric nebulae',
  'A squirrel rendered in Monet’s “Water Lilies” brushwork, swirling pastel garden',
  'A crochet bowl shaped like a grinning pumpkin monster, steam curling from its stitched eyes',
  'A plush toy dinosaur lounging against a mint-green wall, soft-focus editorial shot',
  'A vaporwave dawn over mirrored mountains, digital art with glowing wireframe grids',
  'Twin neo-futuristic spires linked by a hanging garden bridge, concept art with lens flare',
  'Digital concept art of a lunar research base on Europa, domed habitats and icy caverns',
  '3D render of a candy-striped parachute drifting over a mirrored salt flat at sunrise',
  'Retro comic book cover: a DJ hero blasting sonic waves with neon headphones, halftone splashes',
  'A burst of fluorescent powders suspended in midair on an obsidian backdrop, high-speed capture',
  'Candid portrait of a Pomeranian hugging a tuxedo kitten, tongue out, golden-hour light',
  'Photo of a fuzzy blue monster standing in a mint-walled studio, surreal editorial vibe',
  'Stage-lit portrait of an opera singer center-stage, velvet drapes and warm spotlight',
  "Photo of Venus de Milo wearing retro aviator goggles, marble meets modern remix",
  'A knight riding a unicorn across the Martian dunes, lomographic film grain',
  'A vintage Cadillac winding along Vancouver’s Seawall at dusk, lens flare, 35mm film look',
  'A hyperreal headshot of a young man with amber eyes and raven-black hair',
  'A lone explorer stepping through a crystalline portal to another realm, ethereal fantasy art',
  'Bugs Bunny stumbling through a grainy Blair Witch–style forest, found-footage effect',
  'A Triceratops manning a taco truck on a neon street corner, washed-out lomography',
  'Street-style 50mm shot of a woman wandering Seoul’s rain-slick alleys under neon signs',
  'An animated Pixar-style toaster with googly eyes, chiseling out a cheerful grin',
  'Interior of a cyberpunk nightclub with holo-dancers and pulsating neon beams',
  'Poster for “Galaxy Wars: 1990 Anime Saga,” cel-shaded heroes and retro Japanese typography',
  'Abstract oil composition inspired by a jam-packed London tube at rush hour, bold brushwork',
  'Gourmet food photo of a Sudoku-patterned pizza, artfully plated with spinning forks',
  'A neon-armored porcupine in a synthwave city, Blade Runner–esque neon rain',
  'Photo of a spaceman meeting a bioluminescent squid on an alien shore, wide-angle realism',
  'Image of a brontosaurus roaming Table Mountain summit, vivid daylight shot',
  'Digital painting of a woman falling head-over-heels for her holographic AI companion, pastel glow',
  'Lomography shot of a mech-pilot cruising Tokyo’s neon backstreets at 3 AM',
  '1920s film-noir photo of a vampire strolling Prohibition-era Chicago, black-and-white grain',
  'A retro-futuristic jetliner slicing through a neon grid sky, synthwave travel poster',
  'Cinematic 50mm frame of a lone ranger wandering rainy Shinjuku neon alleys, blurred reflections',
  'Digital art of a space shuttle arching above Table Mountain at twilight, cosmic lens flare',
  'A lounge sofa carved from a giant watermelon, pastel-suede upholstery, luminescent moonlight',
  'A surreal gouache scene by Frida Kahlo: a tortoise balancing on floating teacups',
  'Plush foxes browsing neon-night bazaars in Marrakech, mosaic-tile illustration',
  'A charcoal and ink portrait by Pablo Picasso of an android playing backgammon',
  'A raccoon alchemist stirring phosphorescent brews in an enchanted forest lab, storybook art',
  'Design a bold street-art tribute to Nelson Mandela, spray-paint stencil style',
  "Macro 85mm portrait of two gerbils roller-skating on a lavender meadow, dreamy bokeh",
  '3D render of a crystal jellyfish drifting through an underwater gallery, deep-sea blues',
  'An interstellar tourist sipping tea at a Martian tea house, retro-futurist neon palette',
  'Oil painting of a llama in Baroque royal attire, velvet cape and gemstone diadem',
  'A Tiffany-style skylight illustrating steaming ramen bowls and sushi rolls in jewel panels',
  'Graphite and watercolor city of floating gardens with autonomous drones, pastel sunrise haze',
  'A sun-drenched glass atrium with gradient pools—one turquoise, one rose—framed by archways, vector graphic',
  'A mystic corgi reading tea leaves in a giant coconut shell, tropical digital illustration',
  '"A Puffin in a Top Hat" painted in the soft pastels of Mary Cassatt, impressionist canvas',
  'Dry-ink sketch of a grumpy hedgehog commanding a starship through neon constellations',
  'A hedgehog in the style of Gustav Klimt’s “Golden Forest,” swirling gilded leaves',
  'A crochet teapot shaped like a grinning jack-o’-lantern, steam curling in handmade yarn',
  'A felted penguin figurine perched beside a mint-frosted wall, soft-focus product shot',
  'A synthwave dawn over a neon desert highway, digital art with chrome reflections',
  'Twin art-deco spires linked by a sky-garden skybridge, cinematic concept art',
  'Digital concept of an orbital greenhouse circling Venus, glass domes and floating walkways',
  '3D render of a polka-dot parachute drifting above a mirrored desert lake at dusk',
  'Retro pulp magazine cover: a radio DJ hero broadcasting sonic booms, halftone accents',
  'A swirl of iridescent powders against a midnight velvet backdrop, macro photography'
];
